title: Dayda
name: 'Army Corps of Engineers, Department of the Army, Department of Defense'
description: >-
  This is a catalog of datasets organized and made more accessible from the Army
  Corps of Engineers, Department of the Army, Department of Defense, providing
  simple dowloadable CSV and JSON files, as well as Postman Collections you can
  use as part of workflows and other automation.
about: This is all about the entity.
source_url: 'http://example.com'
source_contact_type: general
source_phone: +1 555-555-5555
source_email: info@example.com
source_catalog: data.gov
profile_pic: 'https://directory.dayda.org/assets/img/entities/army-corps-of-engineers.png'
favicon: /assets/img/favicon.png
url: >-
  http://army-corps-of-engineers-department-of-the-army-department-of-defense.dayda.org
encoding: utf-8
paginate: 25
paginate_path: '/page:num/'
markdown: kramdown
